### ISSUE TITLE
A special message on Friday the 13th?

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#390]
This is something I've been thinking about for a while. In addition or in place of the usually X days until, what if there is a "Happy Friday the 13th" message for the rest of the year?

**Comment by collinsnji** [comment]
I can work on this one :)

**Comment by collinsnji** [comment]
@samanthakem please, understand open source is not about who makes the fastest PR. It's more about collaborating on a project towards achieving a common goal. Open Source is not a contest of who's a better programmer, but rather how well you can work with others to build solutions to the problems you both care about. In the future, if you want to submit a PR to an issue, please ask who is currently working on it first. If you don't get a response, then you can go a head to claim the issue. People come from all works of life and live in various places around the world you should keep that in mind as well :) Peace ✌️

**Comment by samanthakem** [comment]
I fully agree with you in every single word @collinsnji, that's why I love open source. However you need to keep in mind that delaying to submit a solution, even a simple one like that, might slow down the project development. Another good thing about open source is that you get to see different solutions about the same problem, like I said in my previous comment "Either way, feel free to submit another PR and the maintainer will pick the best one." and I am happy you did. Thanks! 

In fact, your solution is similar to the one I submitted however it does not cover a few cases. In fact, on the day `12/13/2019`, it will not display "Happy Friday the 13th" as expected. Feel free to check the PR I submitted ;)

The only reason I submitted the PR was because, like I said, I have lost opportunities cuz I saw someone took an issue and I passed, months later the issue was still sitting around. You said "I can work on this one :)" 2 days ago, no updates.

Thanks for this project @scrabill, halloween is my favorite holiday!
